server:
  port: 8080

spring:
  application:
    name: sih-security-platform
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wm_security}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  platform:
    default-target: "https://worldmonitor.app"
    semgrep-rules-path: "../scanner/semgrep/worldmonitor-rules.yaml"
    zap-config-path: "../scanner/zap/scan-config.yaml"
    reports-dir: "./reports"
